### ISSUE TITLE
Unable to push workspace.dsl - 413 Payload too large

### ISSUE THREAD

**Issue by albert-dabrowski** [structurizr/cli#141]
### Description

I successfully uploaded workspaces to the time when we hit 413 payload too large
`        at com.structurizr.api.StructurizrClient.putWorkspace(StructurizrClient.java:420)
        at com.structurizr.cli.PushCommand.run(PushCommand.java:137)
        at com.structurizr.cli.StructurizrCliApplication.run(StructurizrCliApplication.java:81)
        at com.structurizr.cli.StructurizrCliApplication.main(StructurizrCliApplication.java:119)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>413 Payload Too Large</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
<body>
  <center><h1>413 Payload Too Large</h1></center>
</body>
</html>
"; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2418)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:749)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:673)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2082)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:805)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4817)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4723)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)
        at com.structurizr.api.ApiResponse.parse(ApiResponse.java:46)
        at com.structurizr.api.StructurizrClient.putWorkspace(StructurizrClient.java:414)
        ... 3 more

> Task :structurizrCliPush FAILED
`
I'm going on vacations so didn't have an opportunity to debug it. Anyway would be good if there are any hints to overcome this once will be back.

### Steps to reproduce

Quite big workspace with something around 100-150 containers, deployments, etc. 
BTW, it's still rendered on Structurizr Lite.

### Severity

Critical

### Priority

Medium

### Resolution

I have no budget, please fix this for free

### More information

For now will not have a time to fix it, but would be forced if there will be no solution

**Comment by simonbrowndotje** [comment]
Cloud or on-premises?

**Comment by albert-dabrowski** [comment]
On-premise, deployed in our own k8s on Tomcat
