### ISSUE TITLE
Output directory not being set to default on MacOS

### ISSUE THREAD

**Issue by fimassuda** [structurizr/cli#16]
When I run the export command without passing the output argument:
```shell
structurizr-cli export -workspace example.dsl -format plantuml
```

I get an `NullPointerException`:

```
Structurizr CLI v1.5.0
Exporting workspace from example.dsl
 - loading workspace from DSL
 - no styles or themes defined; creating default styles
2020-11-17 08:00:58.790 ERROR 45824 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at com.structurizr.cli.StructurizrCliApplication.main(StructurizrCliApplication.java:69) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[structurizr-cli-1.5.0.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109) ~[structurizr-cli-1.5.0.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[structurizr-cli-1.5.0.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[structurizr-cli-1.5.0.jar:na]
Caused by: java.lang.NullPointerException: null
	at java.base/java.io.File.<init>(File.java:279) ~[na:na]
	at com.structurizr.cli.ExportCommand.run(ExportCommand.java:118) ~[classes!/:na]
	at com.structurizr.cli.StructurizrCliApplication.run(StructurizrCliApplication.java:40) ~[classes!/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	... 13 common frames omitted
```

I was assuming the output argument was optional but looking up at the error I ended up [here](https://github.com/structurizr/cli/blob/master/src/main/java/com/structurizr/cli/ExportCommand.java#L118).

Passing the `-o` argument solved for me, but I think it is supposed to work with the workspace parent directory according to the code, right?

I even thought it could be due to be using the brew installation, but I download the .zip and ran the `./structurizr.sh` and returned the same error.

I'm not sure you were aware of this issue and maybe something that is only happening in the MacOS version.

Thanks!

**Comment by simonbrowndotje** [comment]
Thanks!
