### ISSUE TITLE
How to pull a workspace as a DSL file (not JSON)?

### ISSUE THREAD

**Issue by pellea** [structurizr/cli#2]
After seeing the code, I assume it's not possible as it's uses only `saveWorkspaceToJson` and I could not find a flag to change that behavior.

Is it possible to push/pull a DSL file?

**Comment by simonbrowndotje** [comment]
Correct, there's no way to pull a DSL file. The reason is that the Structurizr CLI converts a DSL file to a JSON workspace, and pushes that via the Structurizr web API. Converting a JSON workspace back to a DSL representation is not supported.

**Comment by pellea** [comment]
But I cannot use the push also to import a DSL file into the workspace. Is this not supported also?

**Comment by simonbrowndotje** [comment]
The `push` command assumes the workspace is defined in the DSL format -> https://github.com/structurizr/cli/blob/master/docs/push.md

So, yes, you can push a workspace defined using the DSL to a Structurizr workspace.

**Comment by pellea** [comment]
Okay I found the correct CLI command thanks to your link, the line generated with to id/token on the website is not correct `-workspace 12344` should be replaced by `-id` otherwise we miss the fact that the -workspace flag is really use for something else.

But I still cannot push the DSL sample "Big Bank plc": 
```
46-88e3-fdf202466ed4
Structurizr CLI v1.3.1
Pushing workspace 57341 to https://api.structurizr.com
 - creating new workspace
 - parsing model and views from /home/pellea/dev/structurizr/advz/test.dsl
2020-08-08 10:04:37.222 ERROR 10603 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at com.structurizr.cli.StructurizrCliApplication.main(StructurizrCliApplication.java:48) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_252]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [structurizr-cli-1.3.1.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109) [structurizr-cli-1.3.1.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [structurizr-cli-1.3.1.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [structurizr-cli-1.3.1.jar:na]
Caused by: com.structurizr.dsl.StructurizrDslParserException: Unexpected tokens at line 81: softwareSystemInstance mainframe
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:435) ~[structurizr-dsl-1.0.0.jar!/:na]
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:134) ~[structurizr-dsl-1.0.0.jar!/:na]
        at com.structurizr.cli.PushCommand.run(PushCommand.java:115) ~[classes!/:na]
        at com.structurizr.cli.StructurizrCliApplication.run(StructurizrCliApplication.java:32) [classes!/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        ... 13 common frames omitted
```

**Comment by simonbrowndotje** [comment]
Thanks. The "Big Bank plc" example was updated a few days ago to reflect the addition of software system instances to deployment views via the DSL, although this isn't yet supported in the CLI. There will be a new CLI release soon (in the next few days) to support this. For the moment, you can comment out the two references to `softwareSystemInstance`.
