### ISSUE TITLE
Unable to create relationships from Container instance or deploymentNode to an infrastructureNode

### ISSUE THREAD

**Issue by evilpilaf** [structurizr/cli#8]
When trying to create a DSL which contains a relationship from a deployment node or a container instance to an infrastructure node I get an exception:

```
2020-10-09 11:53:15.390 ERROR 18748 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
        at com.structurizr.cli.StructurizrCliApplication.main(StructurizrCliApplication.java:69) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_261]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_261]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_261]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_261]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [structurizr-cli-1.4.4.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109) [structurizr-cli-1.4.4.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [structurizr-cli-1.4.4.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [structurizr-cli-1.4.4.jar:na]
Caused by: com.structurizr.dsl.StructurizrDslParserException: A relationship between "imageWebApiAppServiceWE" and "aiImageWebApiWE" is not permitted at line 154: imageWebApiAppServiceWE -> aiImageWebApiWE "Push telemetry, logs and metrics"
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:482) ~[structurizr-dsl-1.0.0.jar!/:na]
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:140) ~[structurizr-dsl-1.0.0.jar!/:na]
        at com.structurizr.cli.PushCommand.run(PushCommand.java:120) ~[classes!/:na]
        at com.structurizr.cli.StructurizrCliApplication.run(StructurizrCliApplication.java:36) [classes!/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
```

**Comment by simonbrowndotje** [comment]
Which version of the CLI are you using?

**Comment by evilpilaf** [comment]
Version 1.4.4

**Comment by simonbrowndotje** [comment]
Does this example work for you?

```
workspace {
    model {
        softwaresystem "Name" {
            webApplication = container "Web Application"
        }

        deploymentEnvironment "Live" {
            deploymentNode "AWS" {
                route53 = infrastructureNode "Route 53"
                webApplicationInstance = containerInstance webApplication
            }

            webApplicationInstance -> route53
        }
    }
         
    views {
        deployment * "Live" {
            include *
            autolayout lr
        }

    }
}
```

**Comment by evilpilaf** [comment]
Ok this example showed me where I was wrong, the relationship has to be defined _inside_ the deployment environment, I was doing it outside, along with all other relationships.

It still fails if I try to have the relationship be from a deploymentNode to an infrastructureNode.

```

**Comment by simonbrowndotje** [comment]
Relationships from deployment nodes to infrastructure nodes are not supported at the moment. What's your use case for this?

**Comment by evilpilaf** [comment]
There wasn't any specific use case for it, it was just one of the things I tried when trying to get the idea working.
