### ISSUE TITLE
Element with relationship breaks exports

### ISSUE THREAD

**Issue by pcolby** [structurizr/cli#81]
It seems that the use of an `element` with a relationship results in exports that are invalid.

Here's the simplest example I could reduce it to:

```
workspace {
  model { 
    enterprise "EnterpriseName" {
      softwareSystem = softwaresystem "SoftwareSystemName"
    }
    element "ElementName" {
      this -> softwareSystem
    }
  }
  views {
    systemlandscape SystemLandscape {
      include *
    }
  }
}
```

The above example works perfectly in https://structurizr.com/dsl

However, using the `structurizr-cli` version:

```
structurizr --version
Structurizr CLI v1.19.0
Structurizr DSL v1.19.1
```

When I run:

```
structurizr export -workspace ./example.dsl -format dsl --output tmp
```

The resulting DSL is:

```
workspace "Name" "Description" {

    !impliedRelationships "false" 
    !identifiers "hierarchical" 

    model {
        enterprise "EnterpriseName" {
            SoftwareSystemName = softwareSystem "SoftwareSystemName" 
        }
        2 -> SoftwareSystemName 
    }

    views {
        systemLandscape "SystemLandscape" {
            include SoftwareSystemName 
            include 2 
        }


    }

}
```

Which then results in errors (in other `structurizr-cli` calls, and https://structurizr.com/dsl) like:

> The source element "2" does not exist at line 10: 2 -> SoftwareSystemName

or

```
java.lang.RuntimeException: The source element "2" does not exist
        at com.structurizr.dsl.ExplicitRelationshipParser.parse(ExplicitRelationshipParser.java:37)
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:204)
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:124)
        at com.structurizr.cli.ExportCommand.run(ExportCommand.java:112)
        at com.structurizr.cli.StructurizrCliApplication.run(StructurizrCliApplication.java:36)
        at com.structurizr.cli.StructurizrCliApplication.main(StructurizrCliApplication.java:81)
com.structurizr.dsl.StructurizrDslParserException: The source element "2" does not exist at line 10: 2 -> SoftwareSystemName
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:757)
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:124)
        at com.structurizr.cli.ExportCommand.run(ExportCommand.java:112)
        at com.structurizr.cli.StructurizrCliApplication.run(StructurizrCliApplication.java:36)
        at com.structurizr.cli.StructurizrCliApplication.main(StructurizrCliApplication.java:81)
```

But everything works well (in much more complicated models) if I just comment out the `element`'s relationship, like:

```
    element "ElementName" {
      # this -> softwareSystem
    }
```

Let me know if you need any more info.

Thanks.

**Comment by pcolby** [comment]
Actually, here's a very slightly simpler version:

Input (valid):
```
workspace {
  model { 
    softwareSystem = softwaresystem "SoftwareSystemName"
    element "ElementName" {
      this -> softwareSystem
    }  
  }    
  views {
    systemlandscape SystemLandscape {
      include *
    }  
  }  
}
```

Output (invalid):
```
workspace "Name" "Description" {

    !impliedRelationships "false" 
    !identifiers "hierarchical" 

    model {
        SoftwareSystemName = softwareSystem "SoftwareSystemName" 
        2 -> SoftwareSystemName 
    }

    views {
        systemLandscape "SystemLandscape" {
            include SoftwareSystemName 
            include 2 
        }


    }

}
```
